version: '3.8'

services:
  chroma_db:
    build:
      context: .
      dockerfile: chroma_DB/Dockerfile
    ports:
      - "5432:5432"
      - "5000:5000"
    networks:
      - chromadb_network
    depends_on:
      - pull_model
      - ollama


  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    networks:
      - chromadb_network
  
    
  pull_model:
    image: python:3.8-slim
    depends_on:
      - ollama
    networks:
      - chromadb_network
    command: >
      bash -c "apt-get update && apt-get install -y curl && curl -X POST -H 'Content-Type: application/json' -d '{\"name\":\"gemma\"}' http://ollama:11434/api/pull"

networks:
  chromadb_network:
    driver: bridge
